services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: nikolayshevtsov
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydjangodb
    ports:
      - "5001:5432"
    #volumes:
      #- ./postgres_data:/var/lib/postgresql/data
      #- /opt/homebrew/var/postgres:/var/lib/postgresql/data  # Bind mount

  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Загружаем переменные из .env
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://nikolayshevtsov:admin@db:5432/mydjangodb
