# Generated by Django 5.1.7 on 2025-03-15 17:48

import django.db.models.deletion
import django.utils.timezone
from phonenumber_field.modelfields import PhoneNumberField

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "div_name",
                    models.CharField(max_length=25, verbose_name="Division Name"),
                ),
                (
                    "in_scope",
                    models.BooleanField(
                        help_text="If the division is target for the learning program, check this field"
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Name")),
                (
                    "priority",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="M",
                        max_length=1,
                        verbose_name="Learning Priorities",
                    ),
                ),
                (
                    "reg_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Registration Date",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_learning.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="employee_learning.employee",
                    ),
                ),
                (
                    "tel",
                    PhoneNumberField(
                        verbose_name="Telephone Number",
                        blank=True,
                        null=True,
                        help_text="Enter a valid phone number (e.g. +12125552368)",
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
            ],
        ),
        migrations.CreateModel(
            name="LearningCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Course Title"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("B", "Basic"),
                            ("I", "Intermediate"),
                            ("A", "Advanced"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="Course Level",
                    ),
                ),
                (
                    "employee",
                    models.ManyToManyField(
                        to="employee_learning.employee",
                        verbose_name="Enrolled Employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Course",
                "verbose_name_plural": "Learning Courses",
            },
        ),
    ]
